version: "2"
run:
  go: "1.23"
linters:
  default: all
  disable:
    - depguard
    - err113
    - errcheck
    - exhaustruct
    - gochecknoglobals
    - gochecknoinits
    - gosmopolitan
    - ireturn
    - mnd
    - nlreturn
    - nonamedreturns
    - perfsprint
    - prealloc
    - tagliatelle
    - testpackage
    - varnamelen
    - wrapcheck
  exclusions:
    generated: lax
    presets:
      - comments
      - common-false-positives
      - legacy
      - std-error-handling
    paths:
      - third_party$
      - builtin$
      - examples$
formatters:
  enable:
    - gci
    - gofmt
    - gofumpt
    - goimports
  settings:
    gci:
      sections:
        - standard
        - default
        - prefix(github.com/forensicanalysis/gitfs)
  exclusions:
    generated: lax
    paths:
      - third_party$
      - builtin$
      - examples$
